### ISSUE TITLE
OE1_MEDIATHEK_BASE_URL changed?

### ISSUE THREAD

**Issue by allisgray** [vikingmedia/oe1grabber#1]
Hi,

the OE1_MEDIATHEK_BASE_URL, which you are relying on in your excellent software oe1grabber, changed recently. I could not find a place this moved to however. Can you please look into this issue?

Thanks!

allisgray

**Comment by vikingmedia** [comment]
hey @allisgray, I noticed a relaunch of their webpage but couldn't look into it so far. I've just analyzed the new web page, and I think a can fix this quite easily. Just give me a few days, I'll reply here again as soon as the new version of the script is pushed.

**Comment by vikingmedia** [comment]
ok @allisgray, the new version is online - enjoy!
